/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{jsx,js,ts,tsx}"],
  theme: {
    extend: {
      width: {
        w100: "100%",
        primary: "25rem",
        seconadry: "50rem",
        width20px: "23rem",
        width30px: "15rem",
        width10px: "150px",
        width70: "23rem",
        widithsearch: "8rem",
        widthfooter: "100%",
        wfooter: "10rem",
        wsm: "8rem",
        wsm2: "30rem",
        wsm3: "200px",
        wsm4: "30rem",
        wsm70: "18rem",
        wsmsearch: "5rem",
        wprimaryburger: "42rem",
        wsmburger: "28rem",
        wgirl: "23rem",
        wsmgirl: "30rem",
        maxw: "100%",
        wmenuw: "45rem",
        wmenuw2: "35rem",
        wmenuw22: "34rem",
        wcart: "4rem",
        wcart2: "5rem",
      },
      height: {
        width20px: "21rem",
        height30px: "31rem",
        h20px: "12rem",
        h30px: "5rem",
        hfooter: "9rem",
        width10px: "150px",
        hsm2: "25rem",
        hsm3: "200px",
        hsm4: "15rem",
        wraph: "23rem",
        hm: "42rem",
        hm1: "41rem",
        hcart: "4rem",
        hmcart: "22rem",
        hcheckout: "9.5rem",
      },
      fontSize: {
        pixels15: "16px",
        pixels30: "18px",
        pixels40: "22px",
        pixels50: "30px",
      },
      margin: {
        ml: "22rem",
        msmAbout: "8rem",
        mabout: "18rem",
        mtest: "6rem",
        mtest2: "10rem",
        ml2: "36rem",
      },
    },

    plugins: [],
  },
};
