export let menu = [
  {
    id: 1,
    name: "Cheese Burger",
    ingridients: "pickels,Cheese,Meat,Something",
    img: require("./Assets/cheese.jpg"),
    price: 20,
    Added: false,
    quantity: 1,
    totalPrice: 1,
  },
  {
    id: 2,
    name: "Cheese Burger",
    ingridients: "pickels,Cheese,Meat,Something",
    img: require("./Assets/menucheese.jpg"),
    price: 20,
    Added: false,
    quantity: 1,
    totalPrice: 1,
  },
  {
    id: 3,
    name: "Cheese Burger",
    ingridients: "pickels,Cheese,Meat,Something",
    img: require("./Assets/cheese.jpg"),
    price: 20,
    Added: false,
    quantity: 1,
    totalPrice: 1,
  },
  {
    id: 4,
    name: "Cheese Burger",
    ingridients: "pickels,Cheese,Meat,Something",
    img: require("./Assets/cheesemenu.jpg"),
    price: 20,
    Added: false,
    quantity: 1,
    totalPrice: 1,
  },
  {
    id: 5,
    name: "Cheese Burger",
    ingridients: "pickels,Cheese,Meat,Something",
    img: require("./Assets/cheese.jpg"),
    price: 20,
    Added: false,
    quantity: 1,
    totalPrice: 1,
  },
  {
    id: 6,
    name: "Cheese Burger",
    ingridients: "pickels,Cheese,Meat,Something",
    img: require("./Assets/menucheese.jpg"),
    price: 20,
    Added: false,
    quantity: 1,
    totalPrice: 1,
  },
  {
    id: 7,
    name: "Cheese Burger",
    ingridients: "pickels,Cheese,Meat,Something",
    img: require("./Assets/cheese.jpg"),
    price: 20,
    Added: false,
    quantity: 1,
    totalPrice: 1,
  },
  {
    id: 8,
    name: "Cheese Burger",
    ingridients: "pickels,Cheese,Meat,Something",
    img: require("./Assets/cheesemenu.jpg"),
    price: 20,
    Added: false,
    quantity: 1,
    totalPrice: 1,
  },
];
